#config_version=5
#Base mode for gold (pop bumpers).
#Kicks off Super Gold mode (super pops) when conditions met.

mode:
  start_events: ball_starting
  priority: 500

sound_player:
  bumpers_hit:
    bumpers_hit_sound_pool:
      action: play

shots:
  bumpers:
    switch: s_left_pop_bumper, s_right_pop_bumper, s_bottom_pop_bumper

counters:
  lb_bumpers_count:
    count_events: bumpers_hit
    count_complete_value: 10 #increase to 100 after done testing
    persist_state: true #this keeps the count from ball to ball
    events_when_complete: super_gold_go
    debug: true
  lb_bumpers_resume:
    enable_events: mode_base_started{current_player.super_gold_achieved>0}
    count_events: bumpers_hit
    count_complete_value: 5 #increase to 25 to match AFM
    persist_state: false #resets the count to 0 at ball end 
    events_when_complete: super_gold_resume_go
    debug: true

event_player:
  super_gold_go:
    start_mode_super_gold
  super_gold_resume_go:
    start_mode_super_gold

variable_player:
  bumpers_hit:
    gold: 10 * current_player.gold_multiplier
    score: 10 * current_player.xp_multiplier
    bumpers_hit_total: 1

show_player:
  #could move this to some kind of wizard mode tracker mode?
  mode_gold_base_started{current_player.super_gold_achieved>0}:
    super_gold_achieved:
      loops: 0
  s_left_pop_bumper_active:
    left_bumper_light:
      loops: 0
  s_right_pop_bumper_active:
    right_bumper_light:
      loops: 0
  s_bottom_pop_bumper_active:
    bottom_bumper_light:
      loops: 0

sound_pools:
  bumpers_hit_sound_pool:
    load: preload
    type: random
    track: sfx
    sounds:
      - iMoneyDialogClose
      - iMoneyDialogOpen
      - LootCoinSmall