#config_version=5
#super_gold mode config. Gives bonus gold for pop bumper hits
#test of local editing of super_gold branch

mode:
  start_events: super_gold_start, super_gold_restart, super_gold_go, super_gold_resume_go
  priority: 300

variable_player:
  s_left_pop_bumper_active:
    gold: 30|block
  s_right_pop_bumper_active:
    gold: 30|block
  s_bottom_pop_bumper_active:
    gold: 30|block

show_player:
  mode_super_gold_started:
    super_gold_started:
      loops: 0
    super_gold_acheived:
      show_tokens:
        lights: l_gold_mode