#config_version=5
#super_gold mode config. Gives bonus gold for pop bumper hits

mode:
  start_events: super_gold_start, super_gold_restart, super_gold_go, super_gold_resume_go
  priority: 501

variable_player:
  mode_super_gold_started:
    super_gold_achieved:
      int: 1
      action: set
  bumpers_hit:
    gold: 30 * current_player.xp_multiplier|block 

show_player:
  mode_super_gold_started:
    super_gold_started:
      loops: 0
    super_gold_achieved:
      show_tokens:
        lights: l_gold_mode
  bumpers_hit:
    bumper_flasher:
      loops: 0
      speed: 1