#config_version=5
#super_gold mode config. Gives bonus gold for pop bumper hits

mode:
  start_events: start_mode_super_gold
  priority: 501

variable_player:
  mode_super_gold_started:
    super_gold_achieved:
      int: 1
      action: set
  bumpers_hit:
    gold: 30 * current_player.gold_multiplier|block 

show_player:
  mode_super_gold_started:
    super_gold_started:
      loops: 0
    super_gold_achieved:
      loops: 0
  bumpers_hit:
    bumper_flasher:
      loops: 0