#config_version=5
#This is the World of Warcraft pinball MPF config file basesd on Stern's GOTG Pro pin (Spike2)
#Command to start MPF and MPF-MC with the smart virtual platform is "mpf both -X" issued from the machine folder
#Command to start MPF Monitor is "mpf monitor" issued from the machine folder

hardware:
  platform: spike

spike:
  port: COM5
  baud: 115200
  flow_control: true
  debug: false
  nodes: 0, 1, 8, 9
  runtime_baud: 115200

config:
  - leds.yaml
  - switches.yaml
  - coils.yaml
  - devices.yaml
  - displays.yaml
  - sounds.yaml
  - videos.yaml
  - images.yaml
  - virtual.yaml
  - keyboard.yaml
  - player_vars.yaml

game:
    balls_per_game: 3
    max_players: 5

machine:
  balls_installed: 6
  min_balls: 6

playfields:
  playfield:
    tags: default
    #enable_ball_search: true
    default_source_device: bd_plunger

modes:
  - base
  - tilt
  - super_gold
  - gold_base
  - pvp_lanes_watchdog
  - xp_lanes_watchdog
  - quest_targets_watchdog

assets:
  sounds:
    default:
      load: preload
    voice:
      load: preload
      track: voice
    sfx:
      load: preload
      track: sfx
    music:
      load: preload
      track: music


#TODO (things from reading that I will need to implement)
#achievements and achievement groups (to track modes started/completed towards wizard mode)
#ball_holds (holding a ball [not locking] while a show or video mode plays [possibly mystery award?])
#ball_saves (for new ball save, unlimited drain timers, rez outlanes when lit)
#ball_seasrch (may be automatic--need to include/configure?)
#bonus mode (built in)
#carousel (allows for player selection of modes and bonuses)
#coins and credits (allows for coins and credits and has toggle for free play)
#combo switches (allow for "flipper cancel", AFM skill shot passthru, and status reports)
#extra_balls (awards and tracks "named" extra balls)
#high_score (for entering high scores--can do mode scores and format it)
#logic blocks (counters count events, accruals watch for events in any order, sequences watch for evetns in order)
#counter logic can count AFM pop hits and then post an event to start a Super Jets mode
#counter logic can count the hits needed on the AFM force field to lower it
#counter along with a timer can be used to count combo shots
#accrual can be used to track the 4 martian target hits during Martian Attack
#seems like logic groups are superior to shots/show_groups (can do more)
#accrual would be how you do an AFM super jackpot
#there's a section after this about tying logic blocks to scoring and shows which is confusing
#match mode (built in can do match)
#multiballs (can be until 1 ball left or timed and have autosave timings. May need to adjust eject_timeouts)
#timers can count up or count down. Events can alter their behavior
#service mode is built in and can be customized
#shots should be defined for things
#shot_groups can do things like cycle the return lanes.
#shot_profiles dictate how shots behave when hit
#sequence_shots defien shots that need to be hit in order (is this inferior to logic blocks)
#skill shots can be times based, hit some target before another target, super skill shot, lane-change skill shot
