#config_version=5

lights:
  l_backlight:
    number: 0-0
  l_coin_enable:
    number: 1-0
  l_start_button:
    number: 1-2
  l_tourney_start_button:
    number: 1-3
  l_lockdown_bar:
    channels:
      red:
        number: 1-5
      green:
        number: 1-4
      blue:
        number: 1-7
  l_left_outlane:
    number: 9-51
  l_left_return_lane_left:
    number: 9-52
  l_left_return_lane_right:
    number: 9-53
  l_pvp_mode:
    number: 8-20
  l_gear_mode:
    number: 8-21
  l_craft_mode:
    number: 8-23
  l_explore_mode:
    number: 8-16
  l_gold_mode:
    number: 8-19
  l_quests_mode:
    number: 8-18
  l_level_mode:
    number: 8-17
  l_dungeon_mode:
    number: 8-15
  l_azeroth_mode:
    number: 8-22
  l_tavern_multiball:
    number: 8-9
  l_raid_mode:
    number: 8-10
  l_leeroy_multiball:
    number: 8-13
  l_shoot_again:
    number: 8-11
  l_right_return_lane:
    number: 8-24
  l_right_outlane:
    number: 8-31
  l_left_lane_arrow:
    channels:
      red:
        number: 9-57
      green:
        number: 9-58
      blue:
        number: 9-59
  l_left_lane_x:
    number: 9-63
  l_left_lane_rectangle:
    number: 9-56
  l_loot_left:
    number: 9-37
  l_loot_center:
    number: 9-38
  l_loot_right:
    number: 9-39
  l_left_orbit_arrow:
    channels:
      red:
        number: 9-33
      green:
        number: 9-34
      blue:
        number: 9-35
  l_left_orbit_x:
    number: 9-36
  l_left_orbit_rectangle:
    number: 9-32
  l_flight_arrow:
    channels:
      red:
        number: 9-43
      green:
        number: 9-44
      blue:
        number: 9-45
  l_flight_x:
    number: 9-42
  l_flight_rectangle:
    number: 9-40
  l_flight_multiball:
    number: 9-47
  l_left_ramp_arrow:
    channels:
      red:
        number: 9-21
      green:
        number: 9-22
      blue:
        number: 9-23
  l_left_ramp_x:
    number: 9-24
  l_left_ramp_rectangle:
    number: 9-25
  l_soulstone_target_left:
    number: 9-20
  l_soulstone_target_right:
    number: 9-8
  l_arena_ready:
    number: 9-16
  l_arena_arrow:
    channels:
      red:
        number: 9-17
      green:
        number: 9-18
      blue:
        number: 9-19
  l_arena_x:
    number: 9-31
  l_arena_rectangle:
    number: 9-30
  l_lock_1:
    number: 9-26
  l_lock_2:
    number: 9-27
  l_lock_3:
    number: 9-28
  l_lock_4:
    number: 9-29
  l_ah_arrow:
    channels:
      red:
        number: 8-45
      green:
        number: 8-46
      blue:
        number: 8-47
  l_ah_x:
    number: 8-51
  l_ah_rectangle:
    number: 8-49
  l_ah_multiball:
    number: 8-48
  l_right_ramp_arrow:
    channels:
      red:
        number: 8-42
      green:
        number: 8-43
      blue:
        number: 8-44
  l_right_ramp_x:
    number: 8-52
  l_right_ramp_rectangle:
    number: 8-50
  l_right_orbit_arrow:
    channels:
      red:
        number: 8-37
      green:
        number: 8-38
      blue:
        number: 8-39
  l_right_orbit_x:
    number: 8-32
  l_right_orbit_rectangle:
    number: 8-40
  l_right_scoop_arrow:
    channels:
      red:
        number: 8-25
      green:
        number: 8-26
      blue:
        number: 8-27
  l_right_scoop_x:
    number: 8-30
  l_right_scoop_rectangle:
    number: 8-29
  l_billboard_1:
    number: 8-33
  l_billboard_2:
    number: 8-34
  l_billboard_3:
    number: 8-35
  l_billboard_4:
    number: 8-36
  l_quest_1:
    number: 9-55
  l_quest_2:
    number: 9-46
  l_quest_3:
    number: 9-41
  l_quest_4:
    number: 8-41
  l_quest_5:
    number: 8-28
  l_left_pop_bumper:
    number: 9-9
  l_right_pop_bumper:
    number: 9-10
  l_bottom_pop_bumper:
    number: 9-11
  l_top_lane_left:
    number: 9-12
  l_top_lane_right:
    number: 9-13
  l_ah_RGB:
    channels:
      red:
        number: 8-53
      green:
        number: 8-54
      blue:
        number: 8-55
  l_tavern_flasher:
    number: 8-5
  l_left_ramp_top_flasher:
    number: 9-3
  l_left_ramp_bottom_flasher:
    number: 8-3
  l_right_ramp_top_flasher:
    number: 9-4
  l_right_ramp_bottom_flasher:
    number: 8-4
  l_pop_bumper_flasher:
    number: 9-5
  l_magnet_flasher:
    number: 9-54
  l_drop_target_flasher:
    number: 9-6
  l_coin_door_gi:
    number: 1-1
    #subtype: led #might be "matrix" instead of led but is this needed at all for GI?
  l_top_gi_1:
    number: 9-1
    #subtype: led #might be "matrix" instead of led but is this needed at all for GI?
  l_top_gi_2:
    number: 9-2
    #subtype: led #might be "matrix" instead of led but is this needed at all for GI?
  l_bottom_gi_1:
    number: 8-1
    #subtype: led #might be "matrix" instead of led but is this needed at all for GI?
  l_bottom_gi_2:
    number: 8-2
    #subtype: led #might be "matrix" instead of led but is this needed at all for GI?
  l_backpanel_gi:
    number: 9-0
    #subtype: led #might be "matrix" instead of led but is this needed at all for GI?
