#config_version=5
#super_gold_watchdog. Kicks off Super Gold mode when conditions met.

mode:
  start_events: ball_starting
  priority: 200

shots:
  bumpers:
    switch: s_left_pop_bumper, s_right_pop_bumper, s_bottom_pop_bumper

counters:
  lb_bumpers_count:
    count_events: bumpers_hit
    count_complete_value: 10 #increase to 100 after done testing
    persist_state: true #this keeps the count from ball to ball
    events_when_complete: super_gold_go
    debug: true
  lb_bumpers_resume:
    #this says to enable it if the current_player variable "super_gold_achieved"
    #(set in machine config) is greater than 0
    enable_events: mode_base_started{current_player.super_gold_achieved>0}
    count_events: bumpers_hit
    count_complete_value: 5 #increase to 25 to match AFM
    persist_state: false #resets the count to 0 at ball end 
    events_when_complete: super_gold_resume_go
    debug: true

event_player:
  super_gold_go:
    start_mode_super_gold
  super_gold_resume_go:
    start_mode_super_gold

variable_player:
  bumpers_hit:
    gold: 10
    score: 10

show_player:
  mode_super_gold_watchdog_started{current_player.super_gold_achieved>0}:
    super_gold_achieved:
      show_tokens:
        lights: l_gold_mode