#config_version=5
#xp_lanes_watchdog mode config. This mode should always be running

mode:
  start_events: ball_starting
  priority: 200

shots:
  shot_top_lane_left:
    switches: s_top_lane_left
    show_tokens:
      leds: l_top_lane_left
  shot_top_lane_right:
    switches: s_top_lane_right
    show_tokens:
      leds: l_top_lane_right

shot_groups:
  sg_xp_lanes:
    shots: shot_top_lane_left, shot_top_lane_right
    rotate_left_events: s_left_flipper_button_active
    rotate_right_events: s_right_flipper_button_active
    reset_events:
      sg_xp_lanes_lit_complete: 1s

variable_player:
  s_top_lane_left_active:
    score: 50
  s_top_lane_right_active:
    score: 50
  sg_xp_lanes_lit_complete:
    xp_lanes_completed:
      int: 1
      action: add